import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";


const josefin = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Top pastry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet"></link>
      </head>
      <body className={`${josefin.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
